package pe.edu.unsch.entities;
// Generated 28-jun-2019 18:07:03 by Hibernate Tools 5.3.0.Beta2

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

	private String dniDocente;
	private String nombres;
	private String apellidos;
	private String semestreAcademico;
	private int cargaAcademico;

	public Docente() {
	}

	public Docente(String dniDocente, String nombres, String apellidos, String semestreAcademico, int cargaAcademico) {
		this.dniDocente = dniDocente;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.semestreAcademico = semestreAcademico;
		this.cargaAcademico = cargaAcademico;
	}

	public String getDniDocente() {
		return this.dniDocente;
	}

	public void setDniDocente(String dniDocente) {
		this.dniDocente = dniDocente;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getSemestreAcademico() {
		return this.semestreAcademico;
	}

	public void setSemestreAcademico(String semestreAcademico) {
		this.semestreAcademico = semestreAcademico;
	}

	public int getCargaAcademico() {
		return this.cargaAcademico;
	}

	public void setCargaAcademico(int cargaAcademico) {
		this.cargaAcademico = cargaAcademico;
	}

}
