-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 08:50:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cargabd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cargabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cargabd` DEFAULT CHARACTER SET utf8 ;
USE `cargabd` ;

-- -----------------------------------------------------
-- Table `cargabd`.`Carga_academica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargabd`.`Carga_academica` ;

CREATE TABLE IF NOT EXISTS `cargabd`.`Carga_academica` (
  `idCarga_academica` INT NOT NULL,
  `Horas_semanales` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idCarga_academica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargabd`.`Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargabd`.`Docente` ;

CREATE TABLE IF NOT EXISTS `cargabd`.`Docente` (
  `DniDocente` VARCHAR(8) NOT NULL,
  `Nombres_Apellidos` VARCHAR(45) NOT NULL,
  `idCarga_academica` INT NOT NULL,
  `idSemestre_academico` INT NOT NULL,
  PRIMARY KEY (`DniDocente`),
  UNIQUE INDEX `DniDocente_UNIQUE` (`DniDocente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargabd`.`Semestre_academico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargabd`.`Semestre_academico` ;

CREATE TABLE IF NOT EXISTS `cargabd`.`Semestre_academico` (
  `idSemestre_academico` INT NOT NULL,
  `Semestre_academico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSemestre_academico`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
