package pe.edu.unsch.entities;
// Generated 05-jul-2019 17:30:45 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CargaAcademica generated by hbm2java
 */
@Entity
@Table(name = "CargaAcademica", catalog = "cargabd")
public class CargaAcademica implements java.io.Serializable {

	private int idCargaAcademica;
	private String horasSemanales;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public CargaAcademica() {
	}

	public CargaAcademica(int idCargaAcademica, String horasSemanales) {
		this.idCargaAcademica = idCargaAcademica;
		this.horasSemanales = horasSemanales;
	}

	public CargaAcademica(int idCargaAcademica, String horasSemanales, Set<Docente> docentes) {
		this.idCargaAcademica = idCargaAcademica;
		this.horasSemanales = horasSemanales;
		this.docentes = docentes;
	}
	@Id
	@Column(name = "idCargaAcademica", unique = true, nullable = false, length = 11)
	public int getIdCargaAcademica() {
		return this.idCargaAcademica;
	}

	public void setIdCargaAcademica(int idCargaAcademica) {
		this.idCargaAcademica = idCargaAcademica;
	}
	@Column(name = "horasSemanales", nullable = false, length = 2)
	public String getHorasSemanales() {
		return this.horasSemanales;
	}

	public void setHorasSemanales(String horasSemanales) {
		this.horasSemanales = horasSemanales;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CargaAcademica")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
