package pe.edu.unsch.entities;
// Generated 04-jul-2019 9:16:15 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * CargaAcademica generated by hbm2java
 */
public class CargaAcademica implements java.io.Serializable {

	private int idCargaAcademica;
	private String horasSemanales;
	private Set docentes = new HashSet(0);

	public CargaAcademica() {
	}

	public CargaAcademica(int idCargaAcademica, String horasSemanales) {
		this.idCargaAcademica = idCargaAcademica;
		this.horasSemanales = horasSemanales;
	}

	public CargaAcademica(int idCargaAcademica, String horasSemanales, Set docentes) {
		this.idCargaAcademica = idCargaAcademica;
		this.horasSemanales = horasSemanales;
		this.docentes = docentes;
	}

	public int getIdCargaAcademica() {
		return this.idCargaAcademica;
	}

	public void setIdCargaAcademica(int idCargaAcademica) {
		this.idCargaAcademica = idCargaAcademica;
	}

	public String getHorasSemanales() {
		return this.horasSemanales;
	}

	public void setHorasSemanales(String horasSemanales) {
		this.horasSemanales = horasSemanales;
	}

	public Set getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set docentes) {
		this.docentes = docentes;
	}

}
