package pe.edu.unsch.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 05-jul-2019 17:30:45 by Hibernate Tools 5.3.0.Beta2

/**
 * Docente generated by hbm2java
 */
@Entity
@Table ( name  =  " Docente " , catalog  =  " cargabd " )
public class Docente implements java.io.Serializable {

	private String dniDocente;
	private CargaAcademica cargaAcademica;
	private SemestreAcademico semestreAcademico;
	private String nombresApellidos;

	public Docente() {
	}

	public Docente(String dniDocente, CargaAcademica cargaAcademica, SemestreAcademico semestreAcademico,
			String nombresApellidos) {
		this.dniDocente = dniDocente;
		this.cargaAcademica = cargaAcademica;
		this.semestreAcademico = semestreAcademico;
		this.nombresApellidos = nombresApellidos;
	}

	@Id
	@Column(name = "dniDocente", unique = true, nullable = false, length = 8)
	public String getDniDocente() {
		return this.dniDocente;
	}

	public void setDniDocente(String dniDocente) {
		this.dniDocente = dniDocente;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCargaAcademica", unique = true, nullable = false)
	public CargaAcademica getCargaAcademica() {
		return this.cargaAcademica;
	}

	public void setCargaAcademica(CargaAcademica cargaAcademica) {
		this.cargaAcademica = cargaAcademica;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSemestreAcademico", unique = true, nullable = false)
	public SemestreAcademico getSemestreAcademico() {
		return this.semestreAcademico;
	}

	public void setSemestreAcademico(SemestreAcademico semestreAcademico) {
		this.semestreAcademico = semestreAcademico;
	}
	@Column(name = "nombresApellidos", nullable = false, length = 45)
	public String getNombresApellidos() {
		return this.nombresApellidos;
	}

	public void setNombresApellidos(String nombresApellidos) {
		this.nombresApellidos = nombresApellidos;
	}

}
